### ISSUE TITLE
Hi this is not an issue lol

### ISSUE THREAD

**Issue by Hopson97** [UKSFM99/BTEC#1]
Here is that OpenGL website I showed you earlier in Portsmouth

https://learnopengl.com/

:)

**Comment by UKSFM99** [comment]
cheers mate, also i just realized you are the creator of a cpp version of minecraft a few friends of mine were looking into...thats so cool XD (i need to learn cpp - only know c# and java lol)

Just curious, once i learn opengl and cpp, i have an idea with some mates to build a flight sim. Would you be happy to help?

Regards

**Comment by Hopson97** [comment]
Your friends talked about me, and then you met me? Small world xD

And yeah, that sounds cool man, I'd love to :)

**Comment by Hopson97** [comment]
Also, is there like a better way we can talk? GitHub issues isn't really good this xD

Do you have Discord or something?

**Comment by UKSFM99** [comment]
Yes I have Facebook , WhatsApp, telegram, snapchat

**Comment by Hopson97** [comment]
Sweet, you can add me here https://www.facebook.com/matthew.hopson.90
